### ISSUE TITLE
Conflicting slf4j-api version

### ISSUE THREAD

**Issue by honnix** [java-operator-sdk/kubernetes-webooks-framework#90]
It seems this repo has moved to slf4j-api 2.x, while https://github.com/java-operator-sdk/java-operator-sdk is still on 1.x. This makes code base using both repos (Maven artifacts) non-straight-forward, as 1.x and 2.x are not compatible. I ended up with having:
```xml
    <dependency>
      <groupId>io.javaoperatorsdk</groupId>
      <artifactId>kubernetes-webhooks-framework-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

Would you consider making this repo stay on 1.x, which I think is still a lot more popular according to maven central? @csviri

**Comment by honnix** [comment]
Note that this was bumped in a dependabot PR: https://github.com/java-operator-sdk/kubernetes-webooks-framework/pull/89, which might not be intentionally. As a matter of fact, I do think the combination of slf4j 2.x and log4j-slf4j-impl works, see https://logging.apache.org/log4j/2.x/log4j-slf4j-impl.html

**Comment by csviri** [comment]
Hi @honnix , I started to work on the fix and use `log4j-slf4j2-impl` what should be there, just it makes issues with annotation processing. But anyways I agree with you, to stay with 1.x for the slf4j api and be also consistent with operators.
